[[main]]
    identifier = "home"
    name = "Home"
    url ="/"
    weight = 10
    pre = "home"

[[main]]
    identifier = "about"
    name = "About"
    url ="/about/"
    weight = 20
    pre = "user"

[[main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 50
    pre = "archive"
