mainSections = ["posts"]
avatar = "https://pic4.zhimg.com/80/v2-638f60ebe89b6bb4a402eae083ce6958_1440w.jpg?source=1940ef5c"
subtitle = "昔日玫瑰以其名流芳，今人所持唯玫瑰之名"
description = "这里是 @Vyong 的私人博客"

tagNumber = 36

disqusUserName = "wincer"
backendAPI = "https://api.liuhuirong.com/"

[StaticVendor]
    version = "wir@1.4.2"
    jsSRI = "sha384-MxoQnwAMkM5aEZ4+nZVvlCvlUr0LhihC7nzCkorRq4aR6fBSi0Up/a99msTXBXu9"

[Sitemap]
    changeFreq = "weekly"
    priority = "0.6"
    termPriority = "0.2"

[Category]
    "实验室" = "https://cdn.jsdelivr.net/npm/wir@1.1.0/cate-cover/laboratory.jpg"
    "博客栈" = "https://cdn.jsdelivr.net/npm/wir@1.1.0/cate-cover/bo-inn.jpg"
    "分享境" = "https://cdn.jsdelivr.net/npm/wir@1.1.0/cate-cover/share.jpg"
    "碎碎念" = "https://cdn.jsdelivr.net/npm/wir@1.1.0/cate-cover/thoughts.jpg"
    "文字阁" = "https://cdn.jsdelivr.net/npm/wir@1.1.0/cate-cover/letter.jpg"


