name: Blog Workflow

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.3'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install Yarn
        run: |
          npm install -g rollup yarn
          yarn install
          rollup -c rollup.config.prod.js

      - name: Initial Environment
        env:
          ID_ED25519: ${{secrets.ed25519}}
        run: |
          mkdir -p ~/.ssh
          echo "$ID_ED25519" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Build
        env:
          GOPRIVATE: "github.com/WincerChan"
        run: |
          hugo --minify

      - name: Depoly
        env:
          username: ${{secrets.username}}
          useremail: ${{secrets.useremail}}
        run: |
          cd public
          git init
          git config --global user.name "${username}"
          git config --global user.email "${useremail}"
          git commit -am "Auto Construct"
          git push -f origin master
